definitions:
  models.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  models.ProjectInput:
    properties:
      client_goals:
        items:
          type: string
        type: array
      company_name:
        type: string
      competitors:
        items:
          type: string
        type: array
      constraints:
        type: string
      key_integrations:
        items:
          type: string
        type: array
      project_summary:
        type: string
      target_audience:
        type: string
    type: object
  models.SuccessResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /prompt/execute:
    post:
      consumes:
      - application/json
      description: Processes the project input and executes the AI prompt
      parameters:
      - description: Project Input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ProjectInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Execute AI Prompt
      tags:
      - prompt
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
